### ISSUE TITLE
SCons update to reflect new unit test structure

### ISSUE THREAD

**Issue by zbeekman** [zbeekman/json-fortran#11]
Hi @bruceravel, would you mind taking a look at the [tests-issue-27-issue-30](https://github.com/zbeekman/json-fortran/tree/tests-issue-27-issue-30) branch of json-fortran and help me update the SConstruct file? Here is a comparison of this branch with @jacobwilliams’ master branch: https://github.com/jacobwilliams/json-fortran/compare/master...zbeekman:tests-issue-27-issue-30

Here is a summary of the changes:
 - `tests/` was moved to `src/tests/`
 - `json_example.f90` was modified and split up into a number of individual tests with names matching `jf_test_*.f90` in the `src/tests/` directory that are automatically vacuumed up and compiled using file name globbing in both `build.sh` and in `CMakeLists.txt`. Each one of these is a stand alone program that links against the json-fortran library, with no other dependencies—at least for the time being. The exit status of these unit test programs determines whether the test passed or failed.
 - there is no longer a `json_example.f90` program, as discussed above

Also, I’m not sure why, but when I tried a parallel build with SCons in the past (using the `-j N` flag) the builds would fail. Bonus points if you can help me get the new SConstruct file to build the project in parallel.

**Comment by bruceravel** [comment]
I will take a look-see.

I have no experience with using scons' parallel building capabilities, so I may not get any bonus points.  Drat!

**Comment by zbeekman** [comment]
Thank you, thank you, thank you! 

FWIW, I think the `-j N` capability is supposed to kind of “just work” similar to how Makefiles have a `-j N` flag. I suspect the issue may have something to do with the .mod file(s) fortran outputs which tend to complicate a lot of build systems. For CMake, for example, if a source file produces a mod file, and that source file is used to build multiple executables or libraries, one either has to compile it into it’s own library first or set different Fortran_MODULE_PATHs for each library/executable to support parallel builds. Otherwise CMake will move/overwrite/delete the .mod file needed by one process from another.

**Comment by bruceravel** [comment]
@zbeekman,

I'm mostly there, but I have a few questions and one comment.

The comment: `build.sh` fails for me with
```
Building unit tests...
Build jf_test_1
usage: FoBiS.py [-h] [-v] {build,clean,rule} ...
FoBiS.py: error: unrecognized arguments: -verbose
```
so I am basing scons success off of the behavior of the output of cmake.

1. cmake builds both a static `.a` and a shared `.so`.  I presume that you would like scons to do the same...?
1. Where does the version number `3.0.0` in `libjsonfortran.so.3.0.0` come from?  grepping for `3\.0` does not turn up a file in the repo that clearly defines the version number.  So I find that a bit confusing.
1. Is there value to the file like `jf_test_5_mod.mod` or should I have scons delete them?  Put them someplace in particular?

Thanks,
B

**Comment by zbeekman** [comment]
FoBiS.py just added the verbose flag in a recent release. Feel free to remove `-verbose` in build.sh, or upgrade FoBiS.py `Audi -H pip install --upgrade FoBiS.py`. The `verbose` flag is only informational and doesn't affect the build. I should have removed it anyway. 

The 3.0.0 gets set in CMakeLists.txt` but don't worry about building static and shared versions of the library. The setup for the library doesn't need much/any modification. The issue is rather building (and running?--but we can script that in the shell if Scons doesn't have a good equivalent of `make test`) all the tests.

**Comment by zbeekman** [comment]
Sorry for the typo, on my phone. `Audi` --> `sudo` in the above post. 

I think the above post answers 1 and 2. As for the test ` .mod` files, there's no reason to save them, AFAICT. The library `.mod` is needed but the test module files aren't needed after the tests are linked. 

If you still have questions let me know and I'll answer them back at my desk.

**Comment by bruceravel** [comment]
> Audi --> sudo in the above post. 

Hilarious!

I am not clear on how you intend the tests to work.  Am I supposed to check the return value of the test program?  Parse the screen output?  How is the testing harness intended to work?

Thanks,
B

**Comment by zbeekman** [comment]
Yeah my phone’s auto correct can be annoying…

The tests are based on the return value… no screen parsing required. Each test is just a stand alone program.

I would say don’t worry about the tests unless there’s a “canonical” way Scons would do it and a SCons user would anticipate/expect. (i.e., whatever the equivalent of `make test` is.) And even still running the tests using SCons is just a bonus/extra credit… it would just be nice to get the library and all the tests built.

Travis-ci signals errors on any non-zero exit status (we are using travis to test the library and build systems) so in theory just running the tests will tell us if anything is up with the sons build, and doing this can be achieved in three short lines of shell script.

Thanks again.

**Comment by bruceravel** [comment]
If there is a standard equivalent of "make test" in scons, I cannot figure it out.

Here is a SConstruct file that works with the tests-issue-27-issue-30 branch of your fork.
https://gist.github.com/bruceravel/9a4b6ffb59684a0786c2

If builds the library and the tests.  The 8 tests programs all seem to run correctly.  It cleans everything up correctly with `scons -c`.

I am pretty frustrated that I cannot figure out testing with scons. I have another idea, but I am running out of steam this afternoon.  And I wanted to give you something to work with.

**Comment by bruceravel** [comment]
@zbeekman,

I just updated the gist containing my proposed SConstruct file.  I figured out how to run your tests gracefully.  Yay!

Now doing `scons test` will run your tests.  If any of them fail, you get a message something like:
```
failing: jf_test_1, jf_test_2, jf_test_3, jf_test_4, jf_test_5, jf_test_6, jf_test_7, jf_test_8
```
where the tests that return a non-zero exit status get listed after `failing:`.

Whew!
B

**Comment by zbeekman** [comment]
awesome! Thanks so much for your help. I’ll get this updated, take it for a test-drive and then submit a PR to @jacobwilliams… Just FYI, I will probably end up amending commits to my fork’s feature branch  and use some forced pushes to get them onto github, but I want to make sure that you @bruceravel feel like you are done enough and satisfied before I go rewriting git history, so I don’t mess you up.

**Comment by zbeekman** [comment]
btw, a link to the gist would be much appreciated…

**Comment by bruceravel** [comment]
Sorry for the confusion.  Same gist, I just updated it in place.

If you now go to
https://gist.github.com/bruceravel/9a4b6ffb59684a0786c2
you will find the file I intend you to use.

Around line 63 there is now a section commented as being for testing.

Have a great weekend.
B

**Comment by zbeekman** [comment]
Thanks so much you too! Cheers!

**Comment by zbeekman** [comment]
There were a couple small things that needed fixing on my system… an `import sys` and `basename` from `os.path` but other than that, works like a charm! Bonus points awarded for getting the tests running! :star2:
